version: "2.3"

volumes:
  img:
  pg_data:

services:
  pg_db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=annyka
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U annyka -d postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
  migrate:
    image: migrate/migrate
    depends_on:
      pg_db:
        condition: service_healthy
    volumes:
      - /Users/annyka/GolandProjects/Project1/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://annyka:pass@pg_db/postgres?sslmode=disable", "up" ]
    links:
      - pg_db
  pin_storage:
    image: arkashabigpotato/pin_storage
    volumes:
      - /Users/annyka/GolandProjects/Project1/static/img:/static/img
    ports:
      - 8888:8888
    depends_on:
      pg_db:
        condition: service_healthy
    environment:
      - DB_HOST=pg_db